from tkinter import *
root=Tk()
root.geometry("300x300")
l1=Label(root,bg="red")
l2=Label(root,bg="orange")
l3=Label(root,bg="yellow")
l4=Label(root,bg="green")
l5=Label(root,bg="blue")
l6=Label(root,bg="purple")
l7=Label(root,bg="deep pink")
l8=Label(root,bg="pink")
l9=Label(root,bg="white")
l10=Label(root,bg="yellow")
l11=Label(root,bg="gold")
l12=Label(root,bg="forestgreen")
l13=Label(root,bg="light blue")
l13=Label(root,bg="deepskyblue")
l1.pack(fill="both")
l2.pack(fill="both")
l11.pack(fill="both")
l3.pack(fill="both")
l12.pack(fill="both")
l4.pack(fill="both")
l13.pack(fill="both")
l5.pack(fill="both")
l6.pack(fill="both")
l7.pack(fill="both")
l8.pack(fill="both")
l9.pack(fill="both")
l10.pack(fill="both")
l13.pack(fill="both")




root.mainloop()